// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import { existsSync } from 'node:fs';
import {
  config as dotenvConfig,
  type DotenvConfigOptions,
  type DotenvConfigOutput,
} from 'dotenv';
import { defineConfig } from 'prisma/config';

const env = process.env['NODE_ENV']?.trim() || 'development';
const dotenvFiles = [`.env.${env}.local`, `.env.${env}`, '.env.local', '.env'];

for (const file of dotenvFiles) {
  if (existsSync(file)) {
    (dotenvConfig as (options?: DotenvConfigOptions) => DotenvConfigOutput)({
      path: file,
      override: false,
    });
  }
}

export default defineConfig({
  schema: 'prisma/schema.prisma',
  migrations: {
    path: 'prisma/migrations',
  },
  datasource: {
    url: process.env['DATABASE_URL'],
  },
});
